# Basic config
port=5354

# Do not read the actual /etc/resolv.conf or fallback since android's netd replaces it
no-resolv
no-poll

# Upstream DNS servers (Google/Cloudflare fallback)
server=8.8.8.8
server=1.1.1.1

# Use Re-Malwack's massive ad-blockers list seamlessly!
addn-hosts=/system/etc/hosts

# Custom hotspot blocks
addn-hosts=/data/adb/modules/hotspot_blocker_ksu/blocklist.txt
